<?php
$userClass = new userClass();
$vocabularios = $userClass->vocabulario($id_idioma);
foreach ($vocabularios as $vocabulario) {
    $processed_value = trim($vocabulario->valor);

    match($vocabulario->id_vocabulario) {
        1 => $vocabulario_juntas = $processed_value,
        2 => $vocabulario_color = $processed_value,
        3 => $vocabulario_acabado = $processed_value,
        4 => $vocabulario_cantidad = $processed_value,
        5 => $vocabulario_anadir_carrito = $processed_value,
        6 => $vocabulario_IVA = $processed_value,
        7 => $vocabulario_color_agotado = $processed_value,
        8 => $vocabulario_comprar = $processed_value,
        9 => $vocabulario_envio_gratis = $processed_value,
        10 => $vocabulario_inicio = $processed_value,
        11 => $tl_productos_relacionados = $processed_value,
        12 => $vocabulario_mate = $processed_value,
        13 => $vocabulario_satinado = $processed_value,
        14 => $vocabulario_n_tienda = $processed_value,
        15 => $vocabulario_plazos_envio = $processed_value,
        16 => $vocabulario_formato = $processed_value,
        17 => $vocabulario_datos_personales = $processed_value,
        18 => $vocabulario_selecciona = $processed_value,
        19 => $vocabulario_tramitacion_pedido = $processed_value,
        20 => $vocabulario_mi_pedido = $processed_value,
        22 => $vocabulario_direccion_envio_checkout = $processed_value,
        23 => $vocabulario_direccion_facturacion = $processed_value,
        24 => $vocabulario_editar = $processed_value,
        25 => $vocabulario_articulo = $processed_value,
        26 => $vocabulario_unidades = $processed_value,
        27 => $vocabulario_precio = $processed_value,
        28 => $vocabulario_total = $processed_value,
        29 => $vocabulario_vaciar_carrito = $processed_value,
        30 => $vocabulario_continuar_comprando = $processed_value,
        31 => $vocabulario_numero_articulos = $processed_value,
        32 => $vocabulario_nueva_direccion = $processed_value,
        33 => $vocabulario_igual_direccion_envio = $processed_value,
        34 => $vocabulario_eliminar_direccion = $processed_value,
        35 => $vocabulario_leer_mas = $processed_value,
        36 => $vocabulario_microcemento = $processed_value,
        37 => $vocabulario_microcemento_listo_al_uso = $processed_value,
        38 => $vocabulario_pintura = $processed_value,
        39 => $vocabulario_pintura_azulejos = $processed_value,
        40 => $vocabulario_hormigon_impreso = $processed_value,
        41 => $vocabulario_barniz_mortero_reparador = $processed_value,
        42 => $vocabulario_nosotros = $processed_value,
        43 => $vocabulario_fabrica = $processed_value,
        44 => $vocabulario_distribuidores = $processed_value,
        45 => $vocabulario_tienda = $processed_value,
        46 => $vocabulario_ayuda = $processed_value,
        47 => $vocabulario_calculadora_presupuestos = $processed_value,
        48 => $vocabulario_contacto = $processed_value,
        49 => $vocabulario_politica_privacidad = $processed_value,
        50 => $vocabulario_politica_venta_devolucion = $processed_value,
        51 => $vocabulario_siguenos = $processed_value,
        52 => $vocabulario_reformas_reales = $processed_value,
        53 => $vocabulario_gastos_envio = $processed_value,
        55 => $vocabulario_metodo_pago = $processed_value,
        62 => $vocabulario_debe_introducir_datos = $processed_value,
        63 => $vocabulario_añadidos_a_pedido = $processed_value,
        64 => $vocabulario_añadido_a_pedido = $processed_value,
        65 => $vocabulario_el_carrito_esta_vacio = $processed_value,
        66 => $vocabulario_se_ha_eliminado_articulo = $processed_value,
        67 => $vocabulario_su_pedido_ha_sido_eliminado = $processed_value,
        68 => $vocabulario_mis_productos = $processed_value,
        69 => $vocabulario_ir_al_carrito = $processed_value,
        70 => $vocabulario_tod_no_hay_prod_en_t_carrito = $processed_value,
        71 => $vocabulario_mis_datos = $processed_value,
        72 => $vocabulario_mis_pedidos = $processed_value,
        73 => $vocabulario_cerrar_sesion = $processed_value,
        74 => $vocabulario_debe_introducir_con = $processed_value,
        76 => $vocabulario_cuenta_desactivada = $processed_value,
        77 => $vocabulario_hola= $processed_value,
        78 => $vocabulario_bienvenido_a_smartcret= $processed_value,
        79 => $vocabulario_datos_no_coinciden_con_usuario= $processed_value,
        80 => $vocabulario_bienvenido= $processed_value,
        81 => $vocabulario_formas_parte_de_smartcret= $processed_value,
        82 => $vocabulario_registro_no_completado_contacte_con_smartcret= $processed_value,
        83 => $vocabulario_no_es_posible_realizar_registro= $processed_value,
        84 => $vocabulario_ya_esta_siendo_utilizado= $processed_value,
        85 => $vocabulario_gracias_por_tu_visita= $processed_value,
        86 => $vocabulario_esperemos_que_regreses_prontos= $processed_value,
        87 => $vocabulario_direccion_correo_no_coincide= $processed_value,
        88 => $vocabulario_hemos_enviado_email_con_instrucciones_para_resetear_contraseña= $processed_value,
        89 => $vocabulario_contraseña_ha_cambiado= $processed_value,
        90 => $vocabulario_se_ha_producido_error_no_cambio_contraseña= $processed_value,
        91 => $vocabulario_debes_introducir_cupon_descuento= $processed_value,
        92 => $vocabulario_cerrar = $processed_value,
        93 => $vocabulario_añadir_modificar_datos_personales = $processed_value,
        94 => $vocabulario_datos_personales_panel = $processed_value,
        95 => $vocabulario_nombre = $processed_value,
        96 => $vocabulario_apellidos = $processed_value,
        97 => $vocabulario_dni_nif_nie = $processed_value,
        98 => $vocabulario_empresa = $processed_value,
        99 => $vocabulario_esencial_identificacion_correcta = $processed_value,
        100 => $vocabulario_telefono = $processed_value,
        101 => $vocabulario_indispensable_telefono_valido = $processed_value,
        102 => $vocabulario_cancelar = $processed_value,
        103 => $vocabulario_guardar = $processed_value,
        104 => $vocabulario_nombre_apellido_vacios = $processed_value,
        105 => $vocabulario_nombre_apellido_menor_3 = $processed_value,
        106 => $vocabulario_documento_identidad_no_correcto = $processed_value,
        107 => $vocabulario_telefono_no_letras = $processed_value,
        108 => $vocabulario_telefono_no_correcto = $processed_value,
        109 => $vocabulario_añadir_modificar_direccion_envio = $processed_value,
        110 => $vocabulario_direccion_envio_panel = $processed_value,
        111 => $vocabulario_codigo_postal = $processed_value,
        112 => $vocabulario_ciudad = $processed_value,
        113 => $vocabulario_pais = $processed_value,
        114 => $vocabulario_seleccione = $processed_value,
        115 => $vocabulario_provincia = $processed_value,
        116 => $vocabulario_envios_otros_paises = $processed_value,
        117 => $vocabulario_estados_unidos = $processed_value,
        118 => $vocabulario_espana_andorra_portugal = $processed_value,
        119 => $vocabulario_italia = $processed_value,
        120 => $vocabulario_alemania_austria = $processed_value,
        121 => $vocabulario_resto_europa = $processed_value,
        122 => $vocabulario_francia_belgica_suiza = $processed_value,
        123 => $vocabulario_observaciones = $processed_value,
        // 124 => $vocabulario_cancelar = $processed_value,
        // 125 => $vocabulario_guardar = $processed_value,
        126 => $vocabulario_direccion_codigo_ciudad_vacios = $processed_value,
        127 => $vocabulario_direccion_codigo_ciudad_menor_3 = $processed_value,
        128 => $vocabulario_debe_seleccionar_pais = $processed_value,
        129 => $vocabulario_debe_seleccionar_provincia = $processed_value,
        130 => $vocabulario_codigo_no_corresponde_provincia = $processed_value,
        131 => $vocabulario_añadir_modificar_direccion_facturacion = $processed_value,
        132 => $vocabulario_copiar_datos_envio = $processed_value,
        133 => $vocabulario_particular = $processed_value,
        134 => $vocabulario_autonomo = $processed_value,
        135 => $vocabulario_empresa = $processed_value,
        136 => $vocabulario_esencial_identificacion_correcta = $processed_value,
        // 137 => $vocabulario_nombre = $processed_value,
        138 => $vocabulario_telefono = $processed_value,
        139 => $vocabulario_nombre_apellido_cif_vacios = $processed_value,
        140 => $vocabulario_seleccionar_tipo_cliente = $processed_value,
        141 => $vocabulario_indicar_empresa = $processed_value,
        142 => $vocabulario_telefono_no_letras = $processed_value,
        // 143 => $vocabulario_nombre_apellido_cif_vacios = $processed_value,
        144 => $vocabulario_telefono_no_correcto = $processed_value,
        145 => $vocabulario_direccion_codigo_ciudad_telefono_vacios = $processed_value,
        // 146 => $vocabulario_guardar = $processed_value,
        // 147 => $vocabulario_cancelar = $processed_value,
        148 => $vocabulario_todavia_no_hay_direccion = $processed_value,
        149 => $vocabulario_resumen = $processed_value,
        150 => $vocabulario_tarjeta_credito = $processed_value,
        151 => $vocabulario_total_articulos = $processed_value,
        152 => $vocabulario_introducir_datos = $processed_value,
        153 => $vocabulario_aplicar = $processed_value,
        154 => $vocabulario_cupon_descuento = $processed_value,
        155 => $vocabulario_iva_incluido = $processed_value,
        156 => $vocabulario_pagar_finalizar = $processed_value,
        157 => $vocabulario_plazos_envio = $processed_value,
        158 => $vocabulario_no_posible_entregar_1 = $processed_value,
        159 => $vocabulario_no_posible_entregar_2 = $processed_value,
        160 => $vocabulario_se_ha_eliminado_direccion = $processed_value,
        161 => $vocabulario_error_no_posible_eliminar_direccion = $processed_value,
        162 => $vocabulario_seleccione_estado = $processed_value,
        163 => $vocabulario_fichas_tencicas = $processed_value,
        164 => $vocabulario_contraseñas_no_coinciden = $processed_value,
        165 => $vocabulario_pendiente = $processed_value,
        166 => $vocabulario_enviado = $processed_value,
        167 => $vocabulario_pagado = $processed_value,
        168 => $vocabulario_fecha = $processed_value,
        169 => $vocabulario_pago = $processed_value,
        170 => $vocabulario_envio = $processed_value,
        171 => $vocabulario_factura = $processed_value,
        172 => $vocabulario_contraseña= $processed_value,
        173 => $vocabulario_contraseña_actual = $processed_value,
        174 => $vocabulario_nueva_contraseña = $processed_value,
        175 => $vocabulario_repetir_contraseña = $processed_value,
        176 => $vocabulario_panel_mis_datos = $processed_value,
        177 => $vocabulario_panel_mis_pedidos = $processed_value,
        180 => $vocabulario_termina_oferta = $processed_value,
        181 => $vocabulario_nuevas_ofertas = $processed_value,
        182 => $vocabulario_mas_vendido = $processed_value,
        183 => $vocabulario_dale_play = $processed_value,
        184 => $vocabulario_blog_ultimas_noticias = $processed_value,
        185 => $vocabulario_suscribete_newsletter = $processed_value,
        186 => $vocabulario_suscribirme = $processed_value,
        187 => $vocabulario_colabora = $processed_value,
        188 => $vocabulario_mas_informacion = $processed_value,
        189 => $vocabulario_termina_en_tiempo = $processed_value,
        190 => $vocabulario_kits_microcemento = $processed_value,
        191 => $vocabulario_kits_baños_duchas_cocina = $processed_value,
        192 => $vocabulario_kits_paredes = $processed_value,
        193 => $vocabulario_ellegance_colletion =  $processed_value,
        194 => $vocabulario_enlace_tienda =  $processed_value,
        195 => $vocabulario_procesar_compra =  $processed_value,
        196 => $vocabulario_continuar_comprando =  $processed_value,
        197 => $vocabulario_se_ha_guardado_nueva_direccion = $processed_value,
        198 => $vocabulario_se_ha_producido_un_error = $processed_value,
        199 => $vocabulario_datos_se_han_actualizado = $processed_value,
        200 => $vocabulario_error_no_posible_actualizar_datos = $processed_value,
        201 => $vocabulario_error_no_posible_guardar_direccion = $processed_value,
        202 => $vocabulario_es_necesario_seleccionar_direccion = $processed_value,
        203 => $vocabulario_se_ha_actualizado_direccion_correctamente = $processed_value,
        204 => $vocabulario_error_no_posible_actualizar_direccion= $processed_value,
        205 => $vocabulario_codigo_descuento_introducir = $processed_value,
        206 => $vocabulario_codigo_descuento_inexistente = $processed_value,
        207 => $vocabulario_codigo_descuento_logueado = $processed_value,
        208 => $vocabulario_codigo_descuento_direccion_envio = $processed_value,
        209 => $vocabulario_codigo_descuento_aplicado = $processed_value,
        210 => $vocabulario_codigo_descuento_uso_permitido = $processed_value,
        211 => $vocabulario_codigo_descuento_caducado = $processed_value,
        212 => $vocabulario_codigo_descuento_no_activo = $processed_value,
        213 => $vocabulario_codigo_descuento_no_disponible = $processed_value,
        214 => $vocabulario_codigo_descuento_eliminado = $processed_value,
        215 => $vocabulario_redirigiendo_redsys = $processed_value,
        216 => $vocabulario_tramitando_pedido = $processed_value,
        217 => $vocabulario_lenguaje = $processed_value,
        218 => $vocabulario_aceptar = $processed_value,
        219 => $vocabulario_idioma = $processed_value,
        220 => $vocabulario_vamos_al_tpv = $processed_value,
        221 => $vocabulario_procesando_pedido = $processed_value,
        222 => $vocabulario_debe_seleccionar_direccion_entrega_facturacion = $processed_value,
        223 => $vocabulario_advertencia = $processed_value,
        224 => $vocabulario_reduccion_iva = $processed_value,
        225 => $vocabulario_total_pagar = $processed_value,
        226 => $vocabulario_descuento_aplicado = $processed_value,
        227 => $vocabulario_eliminar_descuento = $processed_value,
        228 => $vocabulario_direccion_facturacion_panel = $processed_value,
        229 => $vocabulario_pedido_finalizado = $processed_value,
        230 => $vocabulario_preparando_pedido = $processed_value,
        231 => $vocabulario_dicen_que_cambiar = $processed_value,
        232 => $vocabulario_subtotal_productos = $processed_value,
        233 => $vocabulario_metodo_pago_solo = $processed_value,
        234 => $vocabulario_datos_envio = $processed_value,
        235 => $vocabulario_datos_facturacion = $processed_value,
        236 => $vocabulario_blog_sin_articulos = $processed_value,
        237 => $vocabulario_algo_esta_fallando = $processed_value,
        238 => $vocabulario_estamos_tristes = $processed_value,
        239 => $vocabulario_no_sabemos_que = $processed_value,
        240 => $vocabulario_si_necesitas_cualquier_cosa = $processed_value,
        241 => $vocabulario_pais_envio = $processed_value,
        242 => $vocabulario_url_tienda_microcemento = $processed_value,
        243 => $vocabulario_direccion_envio_distinta_localizacion = $processed_value,
        244 => $vocabulario_deseas_cambiar_localizacion = $processed_value,
        245 => $vocabulario_debe_introducir_nombre_email_contrasena = $processed_value,
        246 => $vocabulario_contrasenas_no_coinciden = $processed_value,
        247 => $vocabulario_email_no_valido = $processed_value,
        248 => $vocabulario_mensaje_compras_superiores_3000_1 = $processed_value,
        249 => $vocabulario_mensaje_compras_superiores_3000_2 = $processed_value,
        250 => $vocabulario_descuento_iva = $processed_value,
        251 => $vocabulario_total_a_pagar = $processed_value,
        252 => $vocabulario_impuesto_sobre_iva = $processed_value,
        253 => $vocabulario_impuesto_sobre_iva_espana = $processed_value,
        254 => $vocabulario_tienes_introducir_direccion_email = $processed_value,
        255 => $vocabulario_ha_cambiado_ubicacion = $processed_value,
        256 => $vocabulario_no_encontro_combinacion_uid_pass = $processed_value,
        257 => $vocabulario_contrasena_actual_incorrecta = $processed_value,
        258 => $vocabulario_email = $processed_value,
        259 => $vocabulario_antigua_contrasena_nueva_actual_no_coinciden = $processed_value,
        260 => $vocabulario_eliminar_usuario = $processed_value,
        261 => $vocabulario_preguntar_baja = $processed_value,
        262 => $vocabulario_notificar_mail_baja = $processed_value,
        263 => $vocabulario_confirmar = $processed_value,
        264 => $vocabulario_estas_seguro_eliminar_carrito = $processed_value,
        265 => $vocabulario_si_eliminar = $processed_value,
        266 => $vocabulario_eliminar_articulo = $processed_value,
        267 => $vocabulario_total_articulos_2puntos = $processed_value,
        268 => $vocabulario_direccion_envio = $processed_value,
        269 => $vocabulario_avisar_intentos_fallidos = $processed_value,
        270 => $vocabulario_direccion_de_envio_no_coincide_con_geolocalizacion = $processed_value,
        271 => $vocabulario_ofertas = $processed_value,
        272 => $vocabulario_revisa_email_activar_cuenta = $processed_value,
        273 => $vocabulario_aviso_color = $processed_value,
        274 => $vocabulario_texto_aviso_color = $processed_value,
        275 => $vocabulario_nombre_apellidos_no_pueden_estar_vacios = $processed_value,
        276 => $vocabulario_tipo_factura = $processed_value,
        277 => $vocabulario_asegurese_dni_factura_nominal = $processed_value,
        278 => $vocabulario_factura_simplificada = $processed_value,
        279 => $vocabulario_factura_nominal = $processed_value,
        280 => $vocabulario_kits_microcemento_red = $processed_value,
        281 => $vocabulario_pinturas_red = $processed_value,
        282 => $vocabulario_microcemento_listo_al_uso_red = $processed_value,
        283 => $vocabulario_hormigon_impreso_red = $processed_value,
        284 => $vocabulario_imprimaciones_red = $processed_value,
        285 => $vocabulario_sellado_red = $processed_value,
        286 => $vocabulario_mantanimiento_y_limpieza_red = $processed_value,
        287 => $vocabulario_herramientas_red = $processed_value,
        288 => $vocabulario_productos = $processed_value,
        289 => $vocabulario_informacion_requerida = $processed_value,
        290 => $vocabulario_debes_introducir_dni_en_direccion = $processed_value,
        291 => $vocabulario_envios_gratuitos = $processed_value,
        292 => $vocabulario_correo_electronico = $processed_value,
        293 => $vocabulario_sitio_web = $processed_value,
        294 => $vocabulario_mensaje = $processed_value,
        295 => $vocabulario_he_leido_y_acepto_la = $processed_value,
        296 => $vocabulario_politica_de_privacidad = $processed_value,
        297 => $vocabulario_acepto_recibir_comunicaciones = $processed_value,
        298 => $vocabulario_restablecer = $processed_value,
        299 => $vocabulario_gracias_por_contactar_con_nosotros = $processed_value,
        300 => $vocabulario_error_validacion_captchat = $processed_value,
        301 => $vocabulario_quiero_mi_pintura_azulejos = $processed_value,
        302 => $vocabulario_idiomas = $processed_value,
        303 => $vocabulario_debes_introducir_telefono_en_direccion = $processed_value,
        304 => $vocabulario_debes_introducir_dni_telefono_en_direccion = $processed_value,
        305 => $vocabulario_pedido = $processed_value,
        306 => $vocabulario_estado_pago = $processed_value,
        307 => $vocabulario_fecha_pago = $processed_value,
        308 => $vocabulario_estado_envio = $processed_value,
        309 => $vocabulario_fecha_envio = $processed_value,
        310 => $vocabulario_transportista = $processed_value,
        311 => $vocabulario_no_hay_pedidos = $processed_value,
        312 => $vocabulario_ver_mas = $processed_value,
        313 => $vocabulario_volver = $processed_value,
        314 => $vocabulario_nombre_apellidos_email_telefono_no_vacios = $processed_value,
        315 => $vocabulario_nombre_apellidos_3_caracteres = $processed_value,
        316 => $vocabulario_formato_email_invalido = $processed_value,
        317 => $vocabulario_telefono_debe_contener_solo_numeros = $processed_value,
        318 => $vocabulario_nombre_apellido_vacios = $processed_value,
        319 => $vocabulario_ofertas_smartcret = $processed_value,
        320 => $vocabulario_tiempo_limitado = $processed_value,
        321 => $vocabulario_pago_cancelado = $processed_value,
        322 => $vocabulario_error_pago = $processed_value,
        323 => $vocabulario_pago_exito = $processed_value,


        default => null,
    };
}

$vocabularioArray = [];

foreach ($vocabularios as $vocabulario) {
    $processed_value = $vocabulario->valor;

    match($vocabulario->id_vocabulario) {
        6 => $vocabularioArray['vocabulario_IVA'] = $processed_value,
        74 => $vocabularioArray['debe_introducir_con'] = $processed_value,
        75 => $vocabularioArray['direccion_email_incorrecta'] = $processed_value,
        198 => $vocabularioArray['vocabulario_se_ha_producido_un_error'] = $processed_value,
        245 => $vocabularioArray['vocabulario_debe_introducir_nombre_email_contrasena'] = $processed_value,
        246 => $vocabularioArray['vocabulario_contrasenas_no_coinciden'] = $processed_value,
        247 => $vocabularioArray['vocabulario_email_no_valido'] = $processed_value,

        default => null
    };
}
?>
